### PR TITLE
Issue-597: add logs context 

### LINKED ISSUE #597: Improve Logs panel UX
Open http://localhost:3000/d/VtsMXQl7z/test-logs-support
show log context doesn't work (work wrong in Grafana Labs plugin)
image
image

use Explore
filters in logs panel doesn't work

image

image

### PR DESCRIPTION
**Pull request by lunaticusgreen**
fixes #597 
image

image

### CODE REVIEW

File: src/datasource/datasource.ts [hunk 1]
```diff
@@ -163,84 +168,102 @@ export
...
-          refId: 'FORWARD',
-          series: response.data,
-          meta: response.meta,
-        });
+      const response: any = await this._seriesQuery(stmt, requestId + options?.direction);
 
-        return {data: sqlSeries.toLogs()}
-      } else {
-        const timestampColumn = query?.dateTimeColDataType
+      if (!response || !response.rows) {
```
Comment (Slach) [inline src/datasource/datasource.ts:206]: should we throw error here if something wrong with response?

File: src/datasource/datasource.ts [hunk 2]
```diff
@@ -163,84 +168,102 @@ export
...
+          requestId
+        } = this.createQuery(requestOptions, {...query, query: contextDataRequest})
+
+        return this._seriesQuery(stmt, requestId + options?.direction);
+      }
 
-        return {data: sqlSeries.toLogs()}
+      const response: any = await getLogContext()
+
+      if (!response || !response.rows) {
```
Comment (Slach) [inline src/datasource/datasource.ts:254]: the same, I don't like idea know nothing if request return any error

**Review by Slach — CHANGES_REQUESTED** [review]

**Review by Slach — APPROVED** [review]
