### PR TITLE
fix "in" construction regexp

### LINKED ISSUE #705: Can't visualize timeseries from time, category, metric when too many categories
Use
http://localhost:3000/d/clickhouse-queries-analysis/clickhouse-queries-analysis?orgId=1&from=now-24h&to=now&timezone=utc&var-datasource=P7E099F39B84EA795&var-hostname=$__all&var-query_kind=$__all&var-user=$__all&var-exception_code=$__all&var-query_hash=$__all&var-metric=count%28%29&editPanel=25
for reproduced example (ask me about query_log.native.gz for data samples)

Look errors `Too many points to visualize properly.`

image

query
```sql
with 
   (intDiv(toUInt32(event_time), $interval)) as query_finish,
   (intDiv(toUInt32(query_start_time), $interval)) as query_start,
   arrayMap( i -> ( query_start + i ) * $interval * 1000, range(query_finish - query_start + 1) ) as timestamps
SELECT 
    arrayJoin(timestamps) as t,
    normalized_query_hash,
    ${metric:raw} as m
FROM merge(system,'^query_log')
WHERE 
    event_date BETWEEN toDate($__from / 1000) - INTERVAL 1 DAY AND toDate($__to / 1000) + INTERVAL 1 DAY
    AND event_time BETWEEN toDateTime($__from / 1000) - INTERVAL 20 MINUTE AND  toDateTime($__to / 1000) + INTERVAL 20 MINUTE
    AND type!=1
    $conditionalTest(AND hostName() in ($hostname),$hostname)
    $conditionalTest(AND query_kind in ($query_kind),$query_kind)
    $conditionalTest(AND exception_code in ($exception_code),$exception_code)
    $conditionalTest(AND initial_user in ($user),$user)
    AND normalized_query_hash in [$query_hash]
    AND t BETWEEN $__from  AND $__to
GROUP BY normalized_query_hash, t
ORDER BY count(t) OVER(PARTITION BY normalized_query_hash) DESC, sum(m) OVER(PARTITION BY normalized_query_hash) DESC
LIMIT 200 BY t
```

query is correct, but during serialize into timeSeries looks like we still do it wrong, even after fixes for https://github.com/Altinity/clickhouse-grafana/issues/644

### PR DESCRIPTION
**Pull request by lunaticusgreen**
fix #705

### CODE REVIEW

File: pkg/eval_query.go [hunk 1]
```diff
@@ -2098,6 +2103,24 @@ func betweenBraces(query string) string {
 	return subQuery
 }
 
+func betweenBrackets(query string) string {
```
Comment (Slach) [inline pkg/eval_query.go:2106]: betweenSquareBraces more mental name

**Review by Slach — CHANGES_REQUESTED** [review]

**Review by Slach — APPROVED** [review]

**Review by Slach — CHANGES_REQUESTED** [review]
look https://github.com/Altinity/clickhouse-grafana/pull/709#issuecomment-2603060694

lets try to add unit tests which cover new code?
